### ISSUE TITLE
PHP 7.3 may have related issues

### ISSUE THREAD

**Issue by DarkGhostHunter** [orchestral/testbench-dusk#32]
I tried browser testing in TravisCI using Laralve 5.7 and 3.7@dev. While PHP 7.1 and PHP 7.2 test passed, PHP 7.3 didn't. Cannot retrieve the app log since the Facebook Driver returns an exception (could not find the element, or something like that.).

[The culprit](https://travis-ci.com/DarkGhostHunter/Larapoke/jobs/168715373).

**Comment by Keoghan** [comment]
Cool, I’ll try to take a look this week. Being kept a little busy with work 😉

Seen a few bits break with 7.3, the price of progress!

On 7 Jan 2019, at 20:58, Italo <notifications@github.com> wrote:

I tried browser testing in TravisCI using Laralve 5.7 and 3.7@dev. While PHP 7.1 and PHP 7.2 test passed, PHP 7.3 didn't. Cannot retrieve the app log since the Facebook Driver returns an exception (could not find the element, or something like that.).

The culprit.

**Comment by Keoghan** [comment]
@DarkGhostHunter I wonder if this was related to the other issues found with Laravel and PHP7.3 and is now resolved with later versions of PHP 7.3?

**Comment by DarkGhostHunter** [comment]
Nope. I just restarted the job with `orchestra/testbench-dusk (dev-master 976a74d)`. Still the same problem. this may be on Facebook Driver end.

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-dusk/releases/tag/v3.7.0

It should be solved with the latest release but do report back if it doesn't fix it.
